# Docker Engine release 18.06.0+
version: "3.7"

volumes:
    mongodata:

services:
    backend:
        container_name: backend
        build:
            context: ./backend
        image: webshopdocker_backend:latest
        environment:
            - DB_CONNECTION=mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false
            - PORT=8080
        ports:
            - 8080:8080
        depends_on:
            - database
        restart: always

    database:
        container_name: database-mongo
        image: mongo:4.2.5
        env_file:
            - backend/.env
        restart: always
        volumes:
            - mongodata:/data/db
        ports:
            - 3000:27017

    frontend:
        container_name: frontend-angular
        build:
            context: ./frontend
        image: frontend:latest
        depends_on:
            - backend
        ports:
            - 8081:80
        restart: always
        links:
            - backend
