version: '3'
services:
    database:
        image: 'mongo'
        environment:
            - MONGO_INITDB_DATABASE=docker-app
        volumes:
            - mongodata:/data/db
        ports:
            - "27017:27017"
volumes:
    mongodata: